spring:
  application:
    name: activityservice
  mongodb:
    uri: mongodb://localhost:27017/aiactivityfitness
    database: aiactivityfitness


server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.mongodb.driver: INFO

